os: linux
language: go
go:
- 1.12.x
env:
- GO111MODULE=on
services:
  - docker

before_cache:
  # Save tagged docker images
  - docker-compose build
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
cache:
  bundler: true
  directories:
    - $HOME/docker
install: true
script:
  - docker-compose up -d
